# Generated by Django 3.2.9 on 2021-11-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='username',
            new_name='user',
        ),
    ]
